### ISSUE TITLE
Question - what's the newest distro to support old games? 

### ISSUE THREAD

**Issue by AnthraxBass** [lutris/asgard#1]
Hi, 
I'm looking for a new distro to have XFree86 4.0.x, OSS and i386 glibc out-of-the-box . 
Can you recommend something ?

**Comment by strycore** [comment]
Any distro with those component is going to be quite old!

I'm currently experimenting with Ubuntu 6.06 in Qemu and I've managed to install Heroes of Might and Magic and Rune. Because it's in a VM with no support for acceleration, it's very slow for Rune...

**Comment by AnthraxBass** [comment]
Thanks,
P.S.  I hope to see support of the games that have mandatory CD check.

**Comment by strycore** [comment]
Using a VM is a pretty good way to have CD emulation. That said, not sure if I remember a Linux game that needed the CD to play.
